git:
  commitMessage: 'chore(release): v${version}'
  tagAnnotation: 'chore(release): v${version}'
  tagName: 'v${version}'

hooks:
  after:bump:
    - 'npm run build'
    - 'npm run changelog:update'
    - 'npm pack'

# automatic publish from github workflow
npm:
  publish: false
  private: true
  registry: 'OMITTED'
